name: twowiki
prepare_script: scripts/prepare_2wiki.py
splits:
  train:
    kind: raw
    source: data/2wiki/raw/train.json
    offset: 0
    capacity: 167454
  dev:
    kind: raw
    source: data/2wiki/raw/dev.json
    offset: 0
    capacity: 12576
  test:
    kind: raw
    source: data/2wiki/raw/dev.json
    offset: 500
    capacity: 12576
