from __future__ import annotations

from string import Formatter

from graph_memory.query_synthesis.provenance.contracts import (
    MotifType,
    QueryIntent,
    QueryTemplate,
    TemplateCatalog,
)

CATALOG_VERSION = "provenance-templates-v1"

TemplatePair = tuple[MotifType, QueryIntent]
TemplateRows = tuple[tuple[str, str], ...]

_ROWS: dict[TemplatePair, TemplateRows] = {
    ("call_result", "call_result"): (
        ("direct", "What did the {tool_name} call {call_context} return?"),
        ("retrospective", "Looking back at the run, what result came from {tool_name} {call_context}?"),
        ("imperative", "Retrieve the recorded output of {tool_name} {call_context}."),
        ("passive", "Which output was produced when {tool_name} ran {call_context}?"),
        ("explanatory", "Identify the result generated by the {tool_name} execution {call_context}."),
        ("audit", "For the execution audit, report the stored result for {tool_name} {call_context}."),
    ),
    ("value_flow", "upstream_source"): (
        ("direct", "Which earlier output supplied data to {target_tool} {target_context}?"),
        ("retrospective", "Looking back, what prior result was reused by {target_tool} {target_context}?"),
        ("imperative", "Trace the input of {target_tool} {target_context} back to its producing output."),
        ("passive", "What previous result was consumed by {target_tool} {target_context}?"),
        ("explanatory", "Identify the upstream tool result that provided the reused value to {target_tool} {target_context}."),
        ("audit", "For provenance review, locate the recorded source output behind {target_tool} {target_context}."),
    ),
    ("value_flow", "downstream_result"): (
        ("direct", "What result did {target_tool} produce after consuming data from {source_tool} {target_context}?"),
        ("retrospective", "After the {source_tool} output was reused, what did {target_tool} return {target_context}?"),
        ("imperative", "Retrieve the downstream result of {target_tool} that followed the value from {source_tool} {target_context}."),
        ("passive", "Which result was produced by {target_tool} from the value supplied by {source_tool} {target_context}?"),
        ("explanatory", "Identify the final tool output created when {target_tool} consumed the earlier {source_tool} value {target_context}."),
        ("audit", "For the data-flow audit, report the {target_tool} result downstream of {source_tool} {target_context}."),
    ),
    ("value_flow", "complete_chain"): (
        ("direct", "Which outputs show the value transfer from {source_tool} to {target_tool} {target_context}?"),
        ("retrospective", "Looking back, what complete pair of results records the handoff from {source_tool} to {target_tool} {target_context}?"),
        ("imperative", "Recover both ends of the data flow from {source_tool} into {target_tool} {target_context}."),
        ("passive", "Which result chain was formed when {source_tool} data was consumed by {target_tool} {target_context}?"),
        ("explanatory", "Identify the producer and downstream result needed to explain the {source_tool}-to-{target_tool} value flow {target_context}."),
        ("audit", "For provenance review, return the complete output chain linking {source_tool} and {target_tool} {target_context}."),
    ),
    ("artifact_lifecycle", "artifact_origin"): (
        ("direct", "Which earlier output records the creation of {artifact} before {target_tool} used it?"),
        ("retrospective", "Looking back, what result established {artifact} prior to the {target_tool} access?"),
        ("imperative", "Trace {artifact} back to the output that created or updated it before {target_tool}."),
        ("passive", "By which earlier execution output was {artifact} produced before it was read by {target_tool}?"),
        ("explanatory", "Identify the provenance output that explains where {artifact} came from before {target_tool} used it."),
        ("audit", "For the artifact audit, locate the recorded origin output of {artifact} preceding {target_tool}."),
    ),
    ("artifact_lifecycle", "artifact_use"): (
        ("direct", "What output did {target_tool} produce when it later used {artifact} created by {source_tool}?"),
        ("retrospective", "After {source_tool} established {artifact}, what result came from the later {target_tool} access?"),
        ("imperative", "Retrieve the downstream {target_tool} result that used {artifact} after {source_tool}."),
        ("passive", "Which result was produced when {artifact} from {source_tool} was consumed by {target_tool}?"),
        ("explanatory", "Identify the output showing how {artifact} was subsequently used by {target_tool} after {source_tool}."),
        ("audit", "For lifecycle review, report the later {target_tool} output associated with {artifact} from {source_tool}."),
    ),
    ("artifact_lifecycle", "complete_chain"): (
        ("direct", "Which outputs capture the creation and later use of {artifact} from {source_tool} to {target_tool}?"),
        ("retrospective", "Looking back, what full result pair records the lifecycle of {artifact} between {source_tool} and {target_tool}?"),
        ("imperative", "Recover both provenance outputs for {artifact}: its {source_tool} origin and its {target_tool} use."),
        ("passive", "Which output chain was formed as {artifact} was produced by {source_tool} and consumed by {target_tool}?"),
        ("explanatory", "Identify all results needed to explain the observed lifecycle of {artifact} across {source_tool} and {target_tool}."),
        ("audit", "For artifact provenance, return the complete output chain for {artifact} from {source_tool} through {target_tool}."),
    ),
    ("multi_hop_flow", "upstream_source"): (
        ("direct", "Which original output began the {hop_count}-step dependency chain ending at {target_tool}?"),
        ("retrospective", "Looking back across {hop_count} dependency steps, what earliest result ultimately fed {target_tool}?"),
        ("imperative", "Trace the {hop_count}-step path into {target_tool} back to its first output."),
        ("passive", "By which initial result was the {hop_count}-step flow into {target_tool} started?"),
        ("explanatory", "Identify the upstream source output needed to explain the {hop_count}-step provenance path to {target_tool}."),
        ("audit", "For path audit, locate the first recorded output in the {hop_count}-step chain reaching {target_tool}."),
    ),
    ("multi_hop_flow", "downstream_result"): (
        ("direct", "What final result did {target_tool} produce after the {hop_count}-step flow from {source_tool}?"),
        ("retrospective", "After data moved through {hop_count} dependency steps from {source_tool}, what was the {target_tool} result?"),
        ("imperative", "Retrieve the terminal {target_tool} output of the {hop_count}-step chain beginning at {source_tool}."),
        ("passive", "Which final result was produced by {target_tool} through the {hop_count}-step path from {source_tool}?"),
        ("explanatory", "Identify the downstream result that completed the {hop_count}-step provenance flow from {source_tool} to {target_tool}."),
        ("audit", "For path audit, report the final {target_tool} output downstream of {source_tool} across {hop_count} steps."),
    ),
    ("multi_hop_flow", "complete_chain"): (
        ("direct", "Which outputs form the complete {hop_count}-step chain from {source_tool} to {target_tool}?"),
        ("retrospective", "Looking back, what full sequence of results connects {source_tool} with {target_tool} across {hop_count} dependencies?"),
        ("imperative", "Recover every supporting output on the {hop_count}-step provenance path from {source_tool} to {target_tool}."),
        ("passive", "By which complete result chain was {source_tool} connected to {target_tool} over {hop_count} steps?"),
        ("explanatory", "Identify all outputs required to explain the {hop_count}-step dependency path between {source_tool} and {target_tool}."),
        ("audit", "For provenance review, return the entire {hop_count}-step output chain linking {source_tool} and {target_tool}."),
    ),
    ("multi_source_join", "contributing_sources"): (
        ("direct", "Which earlier outputs were combined by {target_tool} {target_context}?"),
        ("retrospective", "Looking back, what source results converged in the {target_tool} call {target_context}?"),
        ("imperative", "Trace every input of {target_tool} {target_context} back to its contributing output."),
        ("passive", "Which prior results were jointly consumed by {target_tool} {target_context}?"),
        ("explanatory", "Identify all upstream outputs needed to explain the combined inputs to {target_tool} {target_context}."),
        ("audit", "For join provenance, list the recorded source outputs behind {target_tool} {target_context}."),
    ),
    ("multi_source_join", "downstream_result"): (
        ("direct", "What result did {target_tool} produce after combining outputs from {source_tools} {target_context}?"),
        ("retrospective", "After the {source_tools} results converged, what did {target_tool} return {target_context}?"),
        ("imperative", "Retrieve the downstream {target_tool} output created from the combined {source_tools} sources {target_context}."),
        ("passive", "Which result was produced by {target_tool} from the jointly consumed {source_tools} outputs {target_context}?"),
        ("explanatory", "Identify the result that completed the multi-source join from {source_tools} into {target_tool} {target_context}."),
        ("audit", "For join provenance, report the {target_tool} result downstream of {source_tools} {target_context}."),
    ),
    ("multi_source_join", "complete_chain"): (
        ("direct", "Which outputs show the complete join from {source_tools} into {target_tool} {target_context}?"),
        ("retrospective", "Looking back, what full set of results records the convergence of {source_tools} at {target_tool} {target_context}?"),
        ("imperative", "Recover all source outputs and the downstream result for the {source_tools}-to-{target_tool} join {target_context}."),
        ("passive", "By which complete output set were the {source_tools} results combined through {target_tool} {target_context}?"),
        ("explanatory", "Identify every supporting result needed to explain the multi-source join from {source_tools} to {target_tool} {target_context}."),
        ("audit", "For join audit, return the complete provenance output set around {target_tool} and {source_tools} {target_context}."),
    ),
}


def _required_slots(text: str) -> tuple[str, ...]:
    return tuple(
        sorted(
            {
                field_name
                for _, field_name, _, _ in Formatter().parse(text)
                if field_name is not None
            }
        )
    )


def build_default_catalog() -> TemplateCatalog:
    templates: list[QueryTemplate] = []
    for (motif_type, query_intent), rows in _ROWS.items():
        for index, (style, text) in enumerate(rows, start=1):
            templates.append(
                QueryTemplate(
                    template_id=(
                        f"{CATALOG_VERSION}:{motif_type}:{query_intent}:{index:02d}"
                    ),
                    catalog_version=CATALOG_VERSION,
                    motif_type=motif_type,
                    query_intent=query_intent,
                    style_tags=(style,),
                    text=text,
                    required_slots=_required_slots(text),
                )
            )
    return TemplateCatalog(version=CATALOG_VERSION, templates=tuple(templates))


DEFAULT_TEMPLATE_CATALOG = build_default_catalog()


__all__ = [
    "CATALOG_VERSION",
    "DEFAULT_TEMPLATE_CATALOG",
    "build_default_catalog",
]
